apiVersion: omnivol.smoothify.com/v1alpha1
kind: BackupPolicy
metadata:
  labels:
    app.kubernetes.io/name: omnivol
    app.kubernetes.io/managed-by: kustomize
  name: backuppolicy-sample
spec:
  # TODO(user): Add fields here
